server:
  port: 8081
  servlet:
    context-path: /dev/api/${spring.application.name}

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/postify
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    host: smtp.gmail.com
    username: khanarfa8879@gmail.com
    password: undm vqep ywln zxns
    port: 587

