server:
  port: 8082
  servlet:
    context-path: /test/api/${spring.application.name}

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/postify
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect